# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [1]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring!

`💡Ishora` numpy.array

In [2]:
arr = np.arange(9)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



In [6]:
zeros = np.zeros(9)
zeros

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [14]:
arr = np.random.randn(2,3)
arr
arr.itemsize

8

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin?


`💡Ishora` np.info

In [16]:
doc_string = np.add.__doc__

print(doc_string)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [23]:
arr = np.zeros(12)
arr[5] = 1
arr


array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [26]:
arr1 = np.arange(20,60)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [27]:
arr1[::-1]

array([59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43,
       42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26,
       25, 24, 23, 22, 21, 20])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [29]:
matritsa = np.arange(12,21).reshape(3,3)
matritsa

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0]





`💡Ishora` np.nonzero

In [33]:
mat = np.array([3, 7, 0, 0, 9, 0])
np.nonzero(mat)

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [41]:
arrr = np.random.rand(2,2,2)
arrr

array([[[0.29934542, 0.00580916],
        [0.75072786, 0.74422731]],

       [[0.77992419, 0.81739484],
        [0.89135318, 0.86719547]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [54]:
arrr1 = np.arange(0,81).reshape(9,9)
max = np.max(arrr1)
min = np.min(arrr1)
max, min

(80, 0)

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [56]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [62]:
arr1 = np.arange(0,18).reshape(6,3)
arr2 = np.arange(18,30).reshape(3,4)
np.dot(arr1,arr2)

array([[  74,   77,   80,   83],
       [ 272,  284,  296,  308],
       [ 470,  491,  512,  533],
       [ 668,  698,  728,  758],
       [ 866,  905,  944,  983],
       [1064, 1112, 1160, 1208]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [3]:
print(sum(range(5),-1))

9


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b
[False False]
a >= b
[False False]
a < b
[ True True]
a <= b
[ True True]
```

In [7]:
a = np.array([1,2])
b = np.array([4,5])
a>b
a >=b
a < b
a <= b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [10]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [12]:
a = [1,2,3,4,6,7,3,7]
b = [3,5,1,3,74,43,123,65,2,7]
np.intersect1d(a,b)

array([1, 2, 3, 7])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [19]:
a = np.random.randn(10,2)
np.trunc(a)

array([[-0.,  0.],
       [-1.,  0.],
       [ 1.,  0.],
       [ 0.,  0.],
       [ 0., -2.],
       [-0., -2.],
       [-1., -1.],
       [ 0.,  0.],
       [ 0.,  1.],
       [-0.,  1.]])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [24]:
ad = np.arange(9).reshape(3,3)
ad

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [31]:
vektor = np.random.rand(10)
sort = np.sort(vektor)
sort

array([0.25771137, 0.38094863, 0.46930148, 0.57644696, 0.6275856 ,
       0.62786358, 0.66188067, 0.81290815, 0.91898828, 0.97511403])

#### 22. Ikki tasodifiy A va B massiv yarating, ularning tengligini tekshiring

`💡Ishora` np.allclose, np.array_equal

In [35]:
A = np.random.randint(10)
B = np.random.randint(10)
d = np.allclose(A,B)
d

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring.


`💡Ishora` np.dot or np.ones

In [44]:
ar6x3 = np.random.randint(10,200,18).reshape(6,3)
ar3x4 = np.random.randint(1,12,12).reshape(3,4)
np.dot(ar6x3,ar3x4)

array([[ 468,  662,  976,  813],
       [1782, 1736, 3026, 2167],
       [ 844,  885, 1516, 1063],
       [1306,  976, 2142,  985],
       [1094, 1130, 1894, 1434],
       [ 645,  754, 1241,  885]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [52]:
arr = np.arange(5)
max = arr.max()
arr[max] = 0
arr

array([0, 1, 2, 3, 0])

#### 25. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


from datetime import datetime, timedelta`💡Ishora` np.datetime64, np.timedelta64

In [61]:
from datetime import datetime, timedelta
bugun = datetime.now()

# Ertangi kun
ertangi_kun = bugun + timedelta(days=1)

# Kecha sana
kecha = bugun - timedelta(days=1)

# Sanani NumPy arrayga o'zlashtirish
sana_array = np.array([kecha, bugun, ertangi_kun])

# Sanalarni ekranga chiqarish
for sana in sana_array:
    print(sana)

2023-10-30 01:50:01.492838
2023-10-31 01:50:01.492838
2023-11-01 01:50:01.492838


#### 26. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [62]:
birinchi_kun = np.datetime64('2016-01-01')

fevral_birinchi_kun = np.datetime64('2016-02-01')

yanvar_sanalar = np.arange(birinchi_kun, fevral_birinchi_kun, np.timedelta64(1, 'D'))

print(yanvar_sanalar)

['2016-01-01' '2016-01-02' '2016-01-03' '2016-01-04' '2016-01-05'
 '2016-01-06' '2016-01-07' '2016-01-08' '2016-01-09' '2016-01-10'
 '2016-01-11' '2016-01-12' '2016-01-13' '2016-01-14' '2016-01-15'
 '2016-01-16' '2016-01-17' '2016-01-18' '2016-01-19' '2016-01-20'
 '2016-01-21' '2016-01-22' '2016-01-23' '2016-01-24' '2016-01-25'
 '2016-01-26' '2016-01-27' '2016-01-28' '2016-01-29' '2016-01-30'
 '2016-01-31']


#### 27. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [66]:
a = np.random.randn(10,2)
np.trunc(a)

array([[ 1.,  0.],
       [ 0.,  0.],
       [ 0., -1.],
       [ 0., -0.],
       [-1.,  0.],
       [-0.,  0.],
       [-1.,  1.],
       [ 0.,  0.],
       [-1., -0.],
       [ 0.,  0.]])

#### 28. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

#### 29. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [74]:
z = np.array([1, 2, 3, 4, 5])
li = []
for i in range(len(z)):
  li.append(i+1)
  for _ in range(3):
    li.append(0)
li

[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5, 0, 0, 0]

#### 30. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]?


`💡Ishora` stride_tricks.as_strided

In [75]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

# b massivini yaratish
b = [a[i:i+4] for i in range(len(a) - 3)]

# b massivini chiqarish
for row in b:
    print(row)

[1, 2, 3, 4]
[2, 3, 4, 5]
[3, 4, 5, 6]
[4, 5, 6, 7]
[5, 6, 7, 8]
[6, 7, 8, 9]
[7, 8, 9, 10]
[8, 9, 10, 11]
[9, 10, 11, 12]
[10, 11, 12, 13]
[11, 12, 13, 14]


#### 31. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [80]:
# Ixtiyoriy sonlardan tashkil topgan massiv yaratish
massiv = np.random.randint(1, 10, size=(10,))

# O'xshash qiymatlar kiritish
oxshash_qiymatlar = [3, 6, 9]

# O'xshash qiymatlarni topuvchi dastur
oxshashlar = [qiymat for qiymat in massiv if qiymat in oxshash_qiymatlar]

# Natijani chiqarish
print("Asl massiv:", massiv)
print("O'xshash qiymatlar:", oxshashlar)

Asl massiv: [5 6 4 6 8 8 3 1 5 8]
O'xshash qiymatlar: [6, 6, 3]


#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`